config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admins/sessions"}
  #get '/admins' => 'admins#index', as: :admin_root
  #namespace :admin do
     # root 'admins#index' # creates user_root_path
  #end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_for :users
  resources :tasks, :only => [:index,:new,:create,:edit,:update,:show]
  resources :projects, :only => [:index,:new,:create,:edit,:update]
  resources :users, :only => [:index,:show]
  #resources :attachments, :only=>[:index,:new,:create]
  resources :project_attachments, :only=>[:index,:new,:create,:show]
  root "users#index"
	get "users/index"
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
	validates :name, presence: true
	validates :name, uniqueness: {scope: :project_id}
	validates :name,:title,:task_time,:status,:task_date, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
	def index
		begin
			if params[:project_id].present?
				@task=Task.all.joins(:project).where(project_id: params[:project_id])
			elsif params[:project][:id].present?
				@task=Task.all.joins(:project).where(project_id: params[:project][:id])
			else
				@task=Task.all.joins(project: :user).where(projects:{users:{id:current_user.id}})
			end
		rescue Exception => e
			@task=Task.all.joins(project: :user).where(projects:{users:{id:current_user.id}})
		end
	end

	def show
		#@task=Task.find_by(project_id: params[:project_id])
	end

	def new
		@task = Task.new
	end

	def edit
		@task=Task.find(params[:id])
	end

	def update
    
    	@task = Task.find(params[:id])

	    if @task.update(task_params)
	      redirect_to tasks_path
	    else
	      render 'tasks/edit'
	    end
  	end

	def create
		@task = Task.new(task_params)
		if @task.save
			redirect_to tasks_path
		else
			render 'tasks/new'
		end
		
	end

	private

	def task_params
		params.require(:task).permit(:project_id,:name,:title,:status,:task_time,:task_date)
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<title>Edit Task</title>
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<!-- Clarity Section -->
<div class="card bg-info text-white">
      <div class="card-body">Edit Task</div>
</div>

<div class="card bg-white text-blue">
      <div class="card-body"><%= link_to "My Tasks", tasks_path, :class => 'navbar-link'%></div>
</div>

  <div class="card bg-white text-blue" align="center">
  <div class="card-body">
  <%= form_for :task, url: task_path(@task),method: :put do |f| %>

      <table cellpadding="15">
      <tr>
          <td><%= f.label :project_id, "Select Project:" %></td>
          <td><%= f.collection_select :project_id, Project.where(:user_id=>current_user.id), :id, :name, :include_blank => true %></td>
      </tr>
      <tr>
          <td><%= f.label :name, "Task Name:" %></td>
          <td><%= f.text_field :name, size: 20 %></td>
      </tr>
      <tr>
          <td><%= f.label :title , "Task Title:" %></td>
          <td><%= f.text_field :title %></td>
      </tr>
      <tr>
          <td><%= f.label :task_time, "Select Hours:" %></td>
          <td><%= f.select :task_time ,[1,2,3,4,5,6,7,8],:include_blank=>true %></td>
      </tr>
      <tr>
          <td><%= f.label :status, "Status:" %></td>
          <td><%= f.select :status, ["Incomplete","Completed"],:include_blank=>true %></td>
      </tr>
      <tr>
          <td><%= f.label :task_date, "Due Date:" %></td>
          <td><%= f.date_field :task_date %></td>
      </tr>
      <tr>
          <td><%= f.submit "Update Task" %></td>
          <td><p style="color:red">
              <% if @task.errors.full_messages.any? %>
              <% @task.errors.full_messages.each do |error_message| %>
              <%= error_message if @task.errors.full_messages.first == error_message %></p>
          </td>
      </tr>
      </table>
  <% end %>
  <% end %>
  <% end %>
  </div>
  </div>
</body>
</html>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<!-- Clarity Section -->
      <div class="card bg-info text-white">
      <div class="card-body">Task Board</div>
      </div>

      <div class="card bg-white text-black">
      <div class="card-body"><%= link_to "Create Task",new_task_path %></div>
      </div>

      <div class="card bg-white text-black">
      <div class="card-body" align="center">
      <div align="right">
        <%= form_for 'project', :url => {:action => "create"}, :method => "get" do |f| %>
      
          <%= f.collection_select :id, Project.where(:user_id=>current_user.id), :id, :name, :include_blank => true, autofocus:true %>&emsp;
          <%= f.submit "Filter Tasks" %>&emsp;&emsp;&emsp;
        <% end %>
      </div>
      <table cellpadding="20">
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Status</th>
          <th>Task_Time</th>
          <th>Due Date</th>
          <th>Project Name</th>
          <th>Edit Task</th>
        </tr>
        <% @task.each do |data| %>
        <tr>
          <td><%= data.name %></td>
          <td><%= data.title %></td>
          <td><%= data.status %></td>
          <td><%= data.task_time %> Hours</td>
          <td><%= data.task_date.strftime("%a %d-%b-%Y")%></td>
          <td><%= link_to data.project.name, tasks_path(project_id: data.project_id) %></td>
          <td><%= link_to "Edit",edit_task_path(data.id) %></td>
          <!-- <td><%= data.task_date.strftime("%A-%d-%b-%Y") %></td> -->
        </tr>
        <% end %>                  
      </table>
      </div>
      </div>
</body>
</html>

app/views/tasks/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>new task</title>
</head>
<body>

<!-- Clarity Section -->
<div class="card bg-info text-white">
      <div class="card-body">Create Task</div>
</div>

<div class="card bg-white text-blue">
      <div class="card-body"><%= link_to "My Tasks", tasks_path, :class => 'navbar-link'%></div>
</div>

  <div class="card bg-white text-blue" align="center">
  <div class="card-body">
  <%= form_for :task, url: tasks_path do |f| %>

      <table cellpadding="15">
      <tr>
          <td><%= f.label :project_id, "Select Project:" %></td>
          <td><%= f.collection_select :project_id, Project.where(:user_id=>current_user.id), :id, :name, :include_blank => true %></td>
      </tr>
      <tr>
          <td><%= f.label :name, "Task Name:" %></td>
          <td><%= f.text_field :name, size: 20 %></td>
      </tr>
      <tr>
          <td><%= f.label :title , "Task Title:" %></td>
          <td><%= f.text_field :title %></td>
      </tr>
      <tr>
          <td><%= f.label :task_time, "Select Hours:" %></td>
          <td><%= f.select :task_time ,[1,2,3,4,5,6,7,8],:include_blank=>true %></td>
      </tr>
      <tr>
          <td><%= f.label :status, "Status:" %></td>
          <td><%= f.select :status, ["Incomplete","Completed"],:include_blank=>true %></td>
      </tr>
      <tr>
          <td><%= f.label :task_date, "Due Date:" %></td>
          <td><%= f.date_field :task_date %></td>
      </tr>
      <tr>
          <td><%= f.submit "Create Task" %></td>
          <td><p style="color:red">
              <% if @task.errors.full_messages.any? %>
              <% @task.errors.full_messages.each do |error_message| %>
              <%= error_message if @task.errors.full_messages.first == error_message %></p>
          </td>
      </tr>
      </table>
  <% end %>
  <% end %>
  <% end %>
  </div>
  </div>
</body>
</html>

app/views/tasks/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Show Tasks</title>
</head>
<body>
<h1>Show Tasks</h1>

   <table cellpadding="20">
      <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Status</th>
      <th>Task_Time</th>
      <th>Due Date</th>
      </tr>
      <tr>
      <td><%= @task.name %></td>
      <td><%= @task.title %></td>
      <td><%= @task.status %></td>
      <td><%= @task.task_time %> Hours</td>
      <td><%= @task.task_date %></td>
      </tr>
      </table>


</body>
</html>