config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admins/sessions"}
  #get '/admins' => 'admins#index', as: :admin_root
  #namespace :admin do
     # root 'admins#index' # creates user_root_path
  #end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_for :users
  resources :tasks, :only => [:index,:new,:create,:edit,:update,:show]
  resources :projects, :only => [:index,:new,:create,:edit,:update]
  resources :users, :only => [:index,:show]
  #resources :attachments, :only=>[:index,:new,:create]
  resources :project_attachments, :only=>[:index,:new,:create,:show]
  root "users#index"
	get "users/index"
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

	# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 #  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	belongs_to :user
	has_many :tasks
	has_many :project_attachments
	validates :name, presence: true
	validates :name, uniqueness: { scope: :user_id }
	validates :project_type, presence: true
	enum project_type: {
    :Simple=>"Simple",
    :Moderate=>"Moderate",
    :Complex=>"Complex"
	}
	#@project = Project.all
    #enum project_type:[:simple,:moderate,:complex]
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	

	def index

		if !params[:project_type].present?
			@project = Project.where(:user_id=>current_user.id)
		else
			@project=Project.where(project_type: params[:project_type],:user_id=>current_user.id)
		end
		
	end

	

	def edit
		@project = Project.find(params[:id])
		#@project1 = Project.where(:project_type=>"Moderate",:user_id=>current_user.id)
	end

	def update
    
    	@project = Project.find(params[:id])

	    if @project.update(project_params)
	      redirect_to projects_path
	    else
	      render 'projects/edit'
	    end
  	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to projects_path
		else
			render 'projects/new'
		end
		
	end

	private

	def project_params
		params.require(:project).permit(:name, :project_type, :user_id)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<title>Edit Project</title>
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<!-- Clarity Section -->
      <div class="card bg-info text-white">
      <div class="card-body">Edit Project</div>
      </div>
      
      <div class="card bg- text-black">
      <div class="card-body"><%= link_to "My Projects", projects_path, :class => 'navbar-link'%></div>
      </div>
      
      <div class="card bg- text-black">
      <div class="card-body" align="center">
      <%= form_for :project, url:project_path(@project),method: :put do |f| %>
      
            <table cellpadding="20">
            <tr>
                  <td><%= f.label :name, "Edit Project Name:" %></td>
                  <td><%= f.text_field :name, autofocus: true %></td>
            </tr>
            <tr>
                  <td><%= f.label :project_type, "Select Project Type:" %></td>
                  <td><%= f.select :project_type, Project.project_types.values,include_blank:true %></td>
                  <td><%= f.hidden_field :user_id,value:current_user.id %></td>
            </tr>
            <tr>
                  <td><%= f.submit "Update Project" %></td>
                  <td>
                        <p style="color:red;">
                        <% if @project.errors.full_messages.any? %>
                        <% @project.errors.full_messages.each do |error_message| %>
                        <%= error_message if @project.errors.full_messages.first == error_message %>
                        </p>
                  </td>
            </tr>
            </table>

      <% end %>
      <% end %>
      <% end %>
      </div>
      </div>
</body>
</html>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Edit Projects</title>
</head>
<body>
<!-- Clarity Section -->

    <div class="card bg-info text-white">
    <div class="card-body">Projects</div>
    </div>

    <div class="card bg-default text-black">
    <div class="card-body">
      <%= link_to "Create Project",new_project_path %> | <%= link_to 'Tasks', tasks_path, :class => 'navbar-link' %> | <%= link_to 'Attachments', project_attachments_path, :class => 'navbar-link' %>
      </div>
    </div>

    <div class="card bg-default text-black">
    <div class="card-body" align="center">
      <table cellpadding="20">
      <tr>
      <th>User Name</th>
      <th>Project Name</th>
      <th>Project Type</th>
      <th>Edit Project</th>
      <th>View Tasks</th>
      </tr>
      <% @project.each do |data| %>
      <tr>
      <td><%= current_user.name %></td>
      <td><%= data.name %></td>
      <td><%= link_to data.project_type,projects_path(project_type: data.project_type)%></td>
      <td><%= link_to "Edit",edit_project_path(data.id) %></td>
      <td><%= link_to "#{data.name} Tasks", tasks_path(project_id: data.id) %></td>
      </tr>
      <% end %>                  
      </table>
    </div>
  </div>
</body>
</html>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Create Project</title>
</head>
<body>

      <div class="card bg-info text-white">
      <div class="card-body">Create Projects</div>
      </div>

      <div class="card bg-white text-black">
      <div class="card-body"><%= link_to "My Projects", projects_path, :class => 'navbar-link'%></div>
      </div>

      <div class="card bg-red text-black">
      <div class="card-body" align="center">
      <%= form_for :project, url: projects_path do |f| %>

            <table cellpadding="20">
            <tr>
                  <td><%= f.label :name, "Enter Project Name:" %></td>
                  <td><%= f.text_field :name, autofocus: true %></td>
            </tr>
            <tr>
                  <td><%= f.label :project_type, "Select Project Type:" %></td>
                  <td><%=f.select:project_type, Project.project_types.values,include_blank:true%></td>
                  <td><%= f.hidden_field :user_id,value:current_user.id %></td>
            </tr>
            <tr>
                  <td>
                        <%= f.submit "Create Project" %>    
                  </td>
                  <td>
                        <p style="color:red;"><% if @project.errors.full_messages.any? %>
                        <% @project.errors.full_messages.each do |error_message| %>
                        <%= error_message if @project.errors.full_messages.first == error_message %>
                        </p> 
                  </td>
            </tr>
            </table>
      
      <% end %>
      <% end %>
      <% end %>
      </div>
      </div>      
</body>
</html>