config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admins/sessions"}
  #get '/admins' => 'admins#index', as: :admin_root
  #namespace :admin do
     # root 'admins#index' # creates user_root_path
  #end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_for :users
  resources :tasks, :only => [:index,:new,:create,:edit,:update,:show]
  resources :projects, :only => [:index,:new,:create,:edit,:update]
  resources :users, :only => [:index,:show]
  #resources :attachments, :only=>[:index,:new,:create]
  resources :project_attachments, :only=>[:index,:new,:create,:show]
  root "users#index"
	get "users/index"
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pmsr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    
  <p class="navbar-text float-right">
    <% if !admin_signed_in? %>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    <% else %>
    Admin Logged in as <strong><%= current_admin.email %></strong>. | 
    <%= link_to 'Edit Profile', edit_admin_registration_path, :class => 'navbar-link' %> | 
    <% end %>
  </p>

  <div class="jumbotron text-center" style="margin-bottom:0;height:15px">
      <h1>Project Management System</h1>
  </div>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= link_to 'Home', root_path, :class => 'navbar-link' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
    <% if user_signed_in? %>
    <span class="navbar-text">
      <%= link_to "Projects", projects_path, :class=>'navbar-link' %> | <%= link_to "Tasks", tasks_path, :class=>'navbar-link' %> | <%= link_to "Attachments", project_attachments_path, :class=>'navbar-link' %> | <%= link_to "Manage 2FA", user_displayqr_path %>
    </span>
    <% else %>
      <% if admin_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Admin Login", new_admin_session_path, :class => 'navbar-link' %>
      <% end %>
    <% end %>
  </div>
</nav>

<!--<div class="container" style="margin-top:30px">
  <div class="row"> 
    <div class="col-sm-4">
      <h2>About Me</h2>
      <h5>Photo of me:</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
      <h3>Some Links</h3>
      <p>Lorem ipsum dolor sit ame.</p>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="#">Active</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Dec 7, 2017</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
      <br>
      <h2>TITLE HEADING</h2>
      <h5>Title description, Sep 2, 2017</h5>
      <div class="fakeimg">Fake Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
  </div>
</div>-->




      <%= yield %>
  </body>
</html>